config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  root "welcome#index"
  get "my_portfolio", to: 'users#my_portfolio'
  get "my_friends", to: 'users#my_friends'
  get "search_stock", to: 'stocks#search'
  get "search_friends", to: 'users#search'
  get "refresh_prices", to: 'stocks#refresh_prices'
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :users, through: :user_stocks


  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    ticker = ticker_symbol.to_s.upcase

    client = authenticate
    begin
      new(ticker: ticker, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue NameError => e
      return nil
    end
  end

  def self.authenticate
    IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex[:publishable_token],
                         secret_token: Rails.application.credentials.iex[:secret_token],
                         endpoint: 'https://sandbox.iexapis.com/v1')
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.update_prices
    current_prices = {}
    client = authenticate
    all.each do |stock|
      current_prices[stock.ticker] = client.price(stock.ticker)
    end
    find_each do |stock|
      stock.update_attribute(:last_price, current_prices[stock.ticker])
    end
    self.all
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def can_track?(ticker_symbol)
    under_stock_limit? && not_yet_tracking?(ticker_symbol)
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def not_yet_tracking?(ticker_symbol)
    stocks.where(ticker: ticker_symbol).empty?
  end

  def full_name
    return first_name + ' ' + last_name if first_name || last_name
    "Anonymous"
  end

  # match any users with text provided in search field
  def self.matches(param)
    results = []
    %w(email first_name last_name).each do |field|
      results << where("#{field} like ?", "%#{param}%")
    end
    results.flatten.uniq.present? ? results.flatten.uniq : nil
  end

  # remove self from list of matches
  def except_current_user(users)
    users.reject{ |user| user.id == self.id }
  end

  def friends_with?(friend)
    friends.include?(friend)
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])


  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend])

    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "You are now following #{friend.first_name}."
    else
      flash[:alert] = "Oops! Something went wrong trying to track #{friend.first_name}."
    end
    redirect_to my_friends_path
  end

  def destroy
    friend = User.find(params[:id]).full_name
    friendship = Friendship.where(user_id: current_user.id, friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "You are no longer following #{friend}."
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])

      if @stock
        respond_to do |format|
          format.js { render partial: 'users/partials/stock_info'}
        end
      else
        respond_to do |format|
          flash.now[:alert] = "No stock was found for #{params[:stock]}"
          format.js { render partial: 'users/partials/stock_info'}
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "You must enter a ticker symbol"
        format.js { render partial: 'users/partials/stock_info'}
      end
    end
  end # search

  def refresh_prices
    
    if Stock.any?
      @updated_stocks = Stock.update_prices
      Rails.logger.debug "updated stocks: #{@updated_stocks.inspect}"
      respond_to do |format|
        format.js { render partial: 'stocks/partials/refresh_prices', locals: {stocks: @updated_stocks} }
      end

    end
  end


end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:stock])

    if stock.blank?
      stock = Stock.new_lookup(params[:stock])
      if stock.name.blank?
        stock.name = "n/a"
      end
      stock.save
    end

    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "#{stock.name} was successfully added to your portfolio."
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from your portfolio."
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @stocks = @user.stocks
  end

  def my_portfolio
    @stocks = current_user.stocks
  end
  
  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends = User.matches(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/partials/friend_info'}
        end
      else
        respond_to do |format|
          flash.now[:alert] = "No friend was found for #{params[:friend]}"
          format.js { render partial: 'users/partials/friend_info'}
        end
      end

    else
      respond_to do |format|
        flash.now[:alert] = "You must enter a name or email address."
        format.js { render partial: 'users/partials/friend_info'}
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FinanceTrackerApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.d-flex.flex-column
    = render "layouts/partials/navbar"
    #page-content.container.mt-5
      = render "layouts/partials/messages"
      = yield

app/views/layouts/partials/_messages.html.haml
- flash.each do |name, msg|
  - msg_type = (name == 'alert') ? %w(alert-danger) : %w(alert-success)
  .alert.alert-dismissible.fade.show.mb-0{ class: msg_type, role: 'alert' }
    = msg
    %button.close{type: 'button', data: { dismiss: 'alert' } }
      %span{ 'aria-hidden' => true } &times;

app/views/layouts/partials/_navbar.html.haml
.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    = link_to "Finance Tracker", root_path, class: %w(navbar-brand)
    %button.navbar-toggler{type: "button", "aria-controls" => "navbarSupportedContent", "aria-expanded" => false, "aria-label" => "Toggle navigation", data: {toggle: "collapse", target: "#navbarSupportedContent"}}
      %span.navbar-toggler-icon

    .collapse.navbar-collapse#navbarSupportedContent
      %ul.navbar-nav.mr-auto
        - if user_signed_in?
          %li.nav-item.active
            = link_to "Portfolio", my_portfolio_path, class: %w(nav-link)
            %span.sr-only= "(current)"
          %li.nav-item
            = link_to "Friends", my_friends_path, class: %w(nav-link)
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle{href: "#", id: "navbarDropdown", role: "button", "data-toggle":"dropdown", "aria-haspopup":true, "aria-expanded": false}
              Profile
            .dropdown-menu{"aria-labelledby": "navbarDropdown"}
              = link_to edit_user_registration_path, class: %w(dropdown-item) do
                .i.fas.fa-edit
                Edit Profile
              %a.dropdown-item{href: "#"}= "Action 2"
              .dropdown-divider
              %a.dropdown-item{href: "#"}= "Action 3"


      %ul.navbar-nav.ml-auto.mr-2

        - if user_signed_in?
          .i.fas.fa-user.user-icon
          %li.nav-item.active
            = link_to "#{current_user.full_name}", my_portfolio_path, class: %w(nav-link)

          =link_to "Logout", destroy_user_session_path, method: :delete, class: %w(btn btn-warning)

app/views/stocks/partials/_refresh_prices.html.haml
= render partial: 'users/partials/user_stock_table', locals: {stocks: @updated_stocks}

app/views/stocks/partials/_refresh_prices.js.erb
console.log("updating prices...");
$('#my-stocks').remove();
$('#user_stocks').append("<%= j render 'stocks/partials/refresh_prices.html.haml'%>")

app/views/stocks/search.html.haml
%h2 #{@stock_price}

app/views/users/my_friends.html.haml
%h1 Friends

.search-area
  %h3 Search Friends
  .form
    = form_tag search_friends_path, remote: true, method: :get do
      .form-group.row
        .col-sm-6.no-right-padding
          = text_field_tag :friend, params[:friend], placeholder: "Name or Email", autofocus: true, class: %w(form-control form-control-large)
        .col-sm.3.no-left-padding
          = button_tag type: :submit, class: %w(btn btn-success) do
            %i.fas.fa-search
#friend_results

#friends
  - if @friends.present?
    = render partial: 'users/partials/friends_table', locals: {friends: @friends}
  - else
    You are not tracking any friends

app/views/users/my_portfolio.html.haml
%h1 My Portfolio

.search-area
  %h3 Search Stock Prices


  .form
    = form_tag search_stock_path, remote: true, method: :get do
      .form-group.row
        .col-sm-6.no-right-padding
          = text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: %w(form-control form-control-large)
        .col-sm-1.no-left-padding
          = button_tag type: :submit, class: %w(btn btn-success) do
            %i.fas.fa-search
        .col-sm-2.pull-left
          = link_to "Refresh Prices", refresh_prices_path, remote: true, class: %w(btn btn-sm btn-info), data: {disable_with: "Updating..."}

#stock_results


#user_stocks
  - if @stocks.present?
    = render partial: 'users/partials/user_stock_table', locals: {stocks: @stocks}

app/views/users/partials/_friend_info.html.haml
.results-block.friend
  = render partial: "layouts/partials/messages"

  - if @friends
    .row
      .col-md-9
        .card.card-header
          %table
            %tbody
              - @friends.each do |friend|
                %tr
                  %td <strong>Name:</strong> #{friend.full_name}
                  %td <strong>Email:</strong> #{friend.email}
                  %td.mr-1= link_to "View Profile", user_path(friend), class: %w(btn btn-sm btn-info friend-profile)
                  - if current_user.friends_with?(friend)
                    %td.badge.badge-secondary= "Already following"
                  - else
                    %td= link_to "Follow Friend?", friendships_path(friend: friend), method: :post, class: %w(btn btn-sm btn-success)

app/views/users/partials/_friend_info.js.erb
$('#friend_results').append("<%= j render 'users/partials/friend_info.html.haml'%>")

app/views/users/partials/_friends_table.html.haml
.row
  .col-md-9
    %table.table.table-hover.table-bordered.mt-3
      %thead>
        %tr>
          %th{scope: "col"}First Name
          %th{scope: "col"}Last Name
          %th{scope: "col"}Email
          %th.text-center Actions
      - friends.each do |friend|
        %tr
          %td #{friend.first_name}
          %td #{friend.last_name}
          %td #{friend.email}
          %td.text-center
            =link_to "View Profile", user_path(friend), class: %w(btn btn-sm btn-info)
            =link_to "Stop following", friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"}, class: %w(btn btn-sm btn-danger)

app/views/users/partials/_stock_info.html.haml
.row.stock
  .col-sm-6
    = render partial: "layouts/partials/messages"

    - if @stock
      .card.card-header
        .symbol <strong>Symbol:</strong> #{@stock.ticker.upcase}
        .name <strong>Name:</strong> #{@stock.name}
        .price <strong>Last Price:</strong> #{number_to_currency(@stock.last_price, precision: 2)}
        - if current_user.can_track?(@stock.ticker)
          = link_to "Add to portfolio", user_stocks_path(user: current_user.id, stock: @stock.ticker), method: :post, class: %w(btn btn-xs btn-success)
        - else
          %span
            .badge.badge-warning
              - if !current_user.under_stock_limit? 
                You are already tracking 10 stocks.
            .badge.badge-info
              - if !current_user.not_yet_tracking?(@stock.ticker)
                You are already tracking this stock
    

app/views/users/partials/_stock_info.js.erb
if ($('.stock').length == 0) {
  $('#stock_results').append("<%= j render 'users/partials/stock_info.html.haml'%>")
} else {
  $('.stock').remove();
  $('#stock_results').append("<%= j render 'users/partials/stock_info.html.haml'%>")
}

app/views/users/partials/_user_stock_table.html.haml
- @user = @user ||= current_user

.row#my-stocks
  .col-md-9
    %table.table.table-hover.table-bordered.mt-3
      %thead>
        %tr>
          %th{scope: "col"}Ticker
          %th{scope: "col"}Name
          %th{scope: "col"}Price
          %th.text-center Actions
      - stocks.each do |stock|
        %tr
          %td.font-weight-bold #{stock.ticker}
          %td #{stock.name}
          %td #{number_to_currency(stock.last_price)}
          - if current_user == @user
            %td 
              =link_to "Remove", user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"}, class: %w(btn btn-sm btn-warning)
          - else #looking at someone else's portfolio
            %td
              - if current_user.can_track?(stock.ticker)
                = link_to "Add to portfolio", user_stocks_path(user: current_user.id, stock: stock.ticker), method: :post, class: %w(btn btn-xs btn-success)
              - else
                - if !current_user.under_stock_limit?
                  .badge.badge-warning
                    You are already tracking 10 stocks.
                - if !current_user.not_yet_tracking?(stock.ticker)
                  .badge.badge-info
                    You are already tracking this stock

app/views/users/show.html.haml
%h1 #{@user.full_name}'s Profile Page

.row
  .col-md-9
    .card.card-header
      %table
        %tbody
          %tr
            %td <strong>Name:</strong> #{@user.full_name}
            %td <strong>Email:</strong> #{@user.email}

            - if current_user.friends_with?(@user)
              %td.badge.badge-secondary= "Already following"
            - else
              %td= link_to "Follow Friend?", friendships_path(friend: @user), method: :post, class: %w(btn btn-sm btn-success)

- if @stocks.present?
  = render partial: 'users/partials/user_stock_table', locals: {stocks: @user.stocks}

app/views/welcome/index.html.haml
%h1 Welcome to the finance tracker app!

=link_to 'Log Out', destroy_user_session_path, method: :delete